server:
  port: 8080                  # Port server chạy
  servlet:
    context-path: /identity   # Context path chung cho API

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity_service" # Kết nối MySQL
    username: root
    password: 814362
  jpa:
    hibernate:
      ddl-auto: update   # Tự tạo/tự update bảng DB theo entity
    show-sql: true       # Log SQL ra console

jwt:
  signerKey: "dDQUxe/9TmZRTqCPATFEHWkNLKmAMsgl0rdQGa2AIjW1J7dj2dAEsNyZVhfjT5rS" # Khóa ký JWT
  issuer: "tavantien.com"     # Issuer của JWT
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds
