server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity_service"
    username: root
    password: 814362
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "dDQUxe/9TmZRTqCPATFEHWkNLKmAMsgl0rdQGa2AIjW1J7dj2dAEsNyZVhfjT5rS"