server:
  port: 8084                  # Port server ch?y
  servlet:
    context-path: /inventory   # Context path chung cho API

spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/inventory_service}
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:814362}
    driver-class-name: "com.mysql.cj.jdbc.Driver"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true